
(cl:in-package :asdf)

(defsystem "robosub_msgs-msg"
  :depends-on (:roslisp-msg-protocol :roslisp-utils :geometry_msgs-msg
               :std_msgs-msg
)
  :components ((:file "_package")
    (:file "BatteryDetailed" :depends-on ("_package_BatteryDetailed"))
    (:file "_package_BatteryDetailed" :depends-on ("_package"))
    (:file "Detection" :depends-on ("_package_Detection"))
    (:file "_package_Detection" :depends-on ("_package"))
    (:file "DetectionArray" :depends-on ("_package_DetectionArray"))
    (:file "_package_DetectionArray" :depends-on ("_package"))
    (:file "Euler" :depends-on ("_package_Euler"))
    (:file "_package_Euler" :depends-on ("_package"))
    (:file "Float32Stamped" :depends-on ("_package_Float32Stamped"))
    (:file "_package_Float32Stamped" :depends-on ("_package"))
    (:file "HydrophoneDeltas" :depends-on ("_package_HydrophoneDeltas"))
    (:file "_package_HydrophoneDeltas" :depends-on ("_package"))
    (:file "ObstaclePos" :depends-on ("_package_ObstaclePos"))
    (:file "_package_ObstaclePos" :depends-on ("_package"))
    (:file "ObstaclePosArray" :depends-on ("_package_ObstaclePosArray"))
    (:file "_package_ObstaclePosArray" :depends-on ("_package"))
    (:file "Position" :depends-on ("_package_Position"))
    (:file "_package_Position" :depends-on ("_package"))
    (:file "PositionArrayStamped" :depends-on ("_package_PositionArrayStamped"))
    (:file "_package_PositionArrayStamped" :depends-on ("_package"))
    (:file "PositionsStamped" :depends-on ("_package_PositionsStamped"))
    (:file "_package_PositionsStamped" :depends-on ("_package"))
    (:file "Trax" :depends-on ("_package_Trax"))
    (:file "_package_Trax" :depends-on ("_package"))
    (:file "control" :depends-on ("_package_control"))
    (:file "_package_control" :depends-on ("_package"))
    (:file "control_status" :depends-on ("_package_control_status"))
    (:file "_package_control_status" :depends-on ("_package"))
    (:file "gamepad" :depends-on ("_package_gamepad"))
    (:file "_package_gamepad" :depends-on ("_package"))
    (:file "joystick" :depends-on ("_package_joystick"))
    (:file "_package_joystick" :depends-on ("_package"))
    (:file "rgb" :depends-on ("_package_rgb"))
    (:file "_package_rgb" :depends-on ("_package"))
    (:file "rgbArray" :depends-on ("_package_rgbArray"))
    (:file "_package_rgbArray" :depends-on ("_package"))
    (:file "thruster" :depends-on ("_package_thruster"))
    (:file "_package_thruster" :depends-on ("_package"))
    (:file "visionPos" :depends-on ("_package_visionPos"))
    (:file "_package_visionPos" :depends-on ("_package"))
    (:file "visionPosArray" :depends-on ("_package_visionPosArray"))
    (:file "_package_visionPosArray" :depends-on ("_package"))
  ))