// Generated by gencpp from file robosub/pneumatic_status.msg
// DO NOT EDIT!


#ifndef ROBOSUB_MESSAGE_PNEUMATIC_STATUS_H
#define ROBOSUB_MESSAGE_PNEUMATIC_STATUS_H

#include <ros/service_traits.h>


#include <robosub/pneumatic_statusRequest.h>
#include <robosub/pneumatic_statusResponse.h>


namespace robosub
{

struct pneumatic_status
{

typedef pneumatic_statusRequest Request;
typedef pneumatic_statusResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct pneumatic_status
} // namespace robosub


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robosub::pneumatic_status > {
  static const char* value()
  {
    return "0f323cba5aea7d87425f39e2a3d5d386";
  }

  static const char* value(const ::robosub::pneumatic_status&) { return value(); }
};

template<>
struct DataType< ::robosub::pneumatic_status > {
  static const char* value()
  {
    return "robosub/pneumatic_status";
  }

  static const char* value(const ::robosub::pneumatic_status&) { return value(); }
};


// service_traits::MD5Sum< ::robosub::pneumatic_statusRequest> should match 
// service_traits::MD5Sum< ::robosub::pneumatic_status > 
template<>
struct MD5Sum< ::robosub::pneumatic_statusRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robosub::pneumatic_status >::value();
  }
  static const char* value(const ::robosub::pneumatic_statusRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robosub::pneumatic_statusRequest> should match 
// service_traits::DataType< ::robosub::pneumatic_status > 
template<>
struct DataType< ::robosub::pneumatic_statusRequest>
{
  static const char* value()
  {
    return DataType< ::robosub::pneumatic_status >::value();
  }
  static const char* value(const ::robosub::pneumatic_statusRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robosub::pneumatic_statusResponse> should match 
// service_traits::MD5Sum< ::robosub::pneumatic_status > 
template<>
struct MD5Sum< ::robosub::pneumatic_statusResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robosub::pneumatic_status >::value();
  }
  static const char* value(const ::robosub::pneumatic_statusResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robosub::pneumatic_statusResponse> should match 
// service_traits::DataType< ::robosub::pneumatic_status > 
template<>
struct DataType< ::robosub::pneumatic_statusResponse>
{
  static const char* value()
  {
    return DataType< ::robosub::pneumatic_status >::value();
  }
  static const char* value(const ::robosub::pneumatic_statusResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOSUB_MESSAGE_PNEUMATIC_STATUS_H
