// Generated by gencpp from file robosub/pneumatic_statusResponse.msg
// DO NOT EDIT!


#ifndef ROBOSUB_MESSAGE_PNEUMATIC_STATUSRESPONSE_H
#define ROBOSUB_MESSAGE_PNEUMATIC_STATUSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robosub
{
template <class ContainerAllocator>
struct pneumatic_statusResponse_
{
  typedef pneumatic_statusResponse_<ContainerAllocator> Type;

  pneumatic_statusResponse_()
    : left_status(0)
    , right_status(0)  {
    }
  pneumatic_statusResponse_(const ContainerAllocator& _alloc)
    : left_status(0)
    , right_status(0)  {
  (void)_alloc;
    }



   typedef uint8_t _left_status_type;
  _left_status_type left_status;

   typedef uint8_t _right_status_type;
  _right_status_type right_status;





  typedef boost::shared_ptr< ::robosub::pneumatic_statusResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robosub::pneumatic_statusResponse_<ContainerAllocator> const> ConstPtr;

}; // struct pneumatic_statusResponse_

typedef ::robosub::pneumatic_statusResponse_<std::allocator<void> > pneumatic_statusResponse;

typedef boost::shared_ptr< ::robosub::pneumatic_statusResponse > pneumatic_statusResponsePtr;
typedef boost::shared_ptr< ::robosub::pneumatic_statusResponse const> pneumatic_statusResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robosub::pneumatic_statusResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robosub::pneumatic_statusResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robosub

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robosub::pneumatic_statusResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robosub::pneumatic_statusResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robosub::pneumatic_statusResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robosub::pneumatic_statusResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robosub::pneumatic_statusResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robosub::pneumatic_statusResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robosub::pneumatic_statusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "92dffd9bdd6009dd920a9710c1ff6809";
  }

  static const char* value(const ::robosub::pneumatic_statusResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x92dffd9bdd6009ddULL;
  static const uint64_t static_value2 = 0x920a9710c1ff6809ULL;
};

template<class ContainerAllocator>
struct DataType< ::robosub::pneumatic_statusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robosub/pneumatic_statusResponse";
  }

  static const char* value(const ::robosub::pneumatic_statusResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robosub::pneumatic_statusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
uint8 left_status\n\
uint8 right_status\n\
\n\
";
  }

  static const char* value(const ::robosub::pneumatic_statusResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robosub::pneumatic_statusResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.left_status);
      stream.next(m.right_status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pneumatic_statusResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robosub::pneumatic_statusResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robosub::pneumatic_statusResponse_<ContainerAllocator>& v)
  {
    s << indent << "left_status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.left_status);
    s << indent << "right_status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.right_status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOSUB_MESSAGE_PNEUMATIC_STATUSRESPONSE_H
