// Generated by gencpp from file robosub/pneumatic_statusRequest.msg
// DO NOT EDIT!


#ifndef ROBOSUB_MESSAGE_PNEUMATIC_STATUSREQUEST_H
#define ROBOSUB_MESSAGE_PNEUMATIC_STATUSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robosub
{
template <class ContainerAllocator>
struct pneumatic_statusRequest_
{
  typedef pneumatic_statusRequest_<ContainerAllocator> Type;

  pneumatic_statusRequest_()
    {
    }
  pneumatic_statusRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }





  enum {
    FIRED = 0u,
    READY = 1u,
    FAULT = 2u,
  };


  typedef boost::shared_ptr< ::robosub::pneumatic_statusRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robosub::pneumatic_statusRequest_<ContainerAllocator> const> ConstPtr;

}; // struct pneumatic_statusRequest_

typedef ::robosub::pneumatic_statusRequest_<std::allocator<void> > pneumatic_statusRequest;

typedef boost::shared_ptr< ::robosub::pneumatic_statusRequest > pneumatic_statusRequestPtr;
typedef boost::shared_ptr< ::robosub::pneumatic_statusRequest const> pneumatic_statusRequestConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robosub::pneumatic_statusRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robosub::pneumatic_statusRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robosub

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robosub::pneumatic_statusRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robosub::pneumatic_statusRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robosub::pneumatic_statusRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robosub::pneumatic_statusRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robosub::pneumatic_statusRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robosub::pneumatic_statusRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robosub::pneumatic_statusRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5a3becc9c0d6446794f8ed0c2f8c2ba2";
  }

  static const char* value(const ::robosub::pneumatic_statusRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5a3becc9c0d64467ULL;
  static const uint64_t static_value2 = 0x94f8ed0c2f8c2ba2ULL;
};

template<class ContainerAllocator>
struct DataType< ::robosub::pneumatic_statusRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robosub/pneumatic_statusRequest";
  }

  static const char* value(const ::robosub::pneumatic_statusRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robosub::pneumatic_statusRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
\n\
\n\
\n\
uint8 FIRED=0\n\
uint8 READY=1\n\
uint8 FAULT=2\n\
\n\
\n\
";
  }

  static const char* value(const ::robosub::pneumatic_statusRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robosub::pneumatic_statusRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pneumatic_statusRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robosub::pneumatic_statusRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::robosub::pneumatic_statusRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // ROBOSUB_MESSAGE_PNEUMATIC_STATUSREQUEST_H
