// Generated by gencpp from file robosub_msgs/joystick.msg
// DO NOT EDIT!


#ifndef ROBOSUB_MSGS_MESSAGE_JOYSTICK_H
#define ROBOSUB_MSGS_MESSAGE_JOYSTICK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robosub_msgs
{
template <class ContainerAllocator>
struct joystick_
{
  typedef joystick_<ContainerAllocator> Type;

  joystick_()
    : axisX(0.0)
    , axisY(0.0)
    , axisZ(0.0)
    , hatX(0)
    , hatY(0)
    , throttle(0.0)
    , buttons()  {
      buttons.assign(false);
  }
  joystick_(const ContainerAllocator& _alloc)
    : axisX(0.0)
    , axisY(0.0)
    , axisZ(0.0)
    , hatX(0)
    , hatY(0)
    , throttle(0.0)
    , buttons()  {
  (void)_alloc;
      buttons.assign(false);
  }



   typedef double _axisX_type;
  _axisX_type axisX;

   typedef double _axisY_type;
  _axisY_type axisY;

   typedef double _axisZ_type;
  _axisZ_type axisZ;

   typedef int32_t _hatX_type;
  _hatX_type hatX;

   typedef int32_t _hatY_type;
  _hatY_type hatY;

   typedef double _throttle_type;
  _throttle_type throttle;

   typedef boost::array<uint8_t, 12>  _buttons_type;
  _buttons_type buttons;





  typedef boost::shared_ptr< ::robosub_msgs::joystick_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robosub_msgs::joystick_<ContainerAllocator> const> ConstPtr;

}; // struct joystick_

typedef ::robosub_msgs::joystick_<std::allocator<void> > joystick;

typedef boost::shared_ptr< ::robosub_msgs::joystick > joystickPtr;
typedef boost::shared_ptr< ::robosub_msgs::joystick const> joystickConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robosub_msgs::joystick_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robosub_msgs::joystick_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robosub_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'robosub_msgs': ['/home/gabrieljsss/ros/src/robosub_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robosub_msgs::joystick_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robosub_msgs::joystick_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robosub_msgs::joystick_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robosub_msgs::joystick_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robosub_msgs::joystick_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robosub_msgs::joystick_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robosub_msgs::joystick_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5527892ffea6437b35d95656023787b7";
  }

  static const char* value(const ::robosub_msgs::joystick_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5527892ffea6437bULL;
  static const uint64_t static_value2 = 0x35d95656023787b7ULL;
};

template<class ContainerAllocator>
struct DataType< ::robosub_msgs::joystick_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robosub_msgs/joystick";
  }

  static const char* value(const ::robosub_msgs::joystick_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robosub_msgs::joystick_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 axisX\n\
float64 axisY\n\
float64 axisZ\n\
\n\
int32 hatX\n\
int32 hatY\n\
\n\
float64 throttle\n\
\n\
bool[12] buttons\n\
";
  }

  static const char* value(const ::robosub_msgs::joystick_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robosub_msgs::joystick_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.axisX);
      stream.next(m.axisY);
      stream.next(m.axisZ);
      stream.next(m.hatX);
      stream.next(m.hatY);
      stream.next(m.throttle);
      stream.next(m.buttons);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct joystick_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robosub_msgs::joystick_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robosub_msgs::joystick_<ContainerAllocator>& v)
  {
    s << indent << "axisX: ";
    Printer<double>::stream(s, indent + "  ", v.axisX);
    s << indent << "axisY: ";
    Printer<double>::stream(s, indent + "  ", v.axisY);
    s << indent << "axisZ: ";
    Printer<double>::stream(s, indent + "  ", v.axisZ);
    s << indent << "hatX: ";
    Printer<int32_t>::stream(s, indent + "  ", v.hatX);
    s << indent << "hatY: ";
    Printer<int32_t>::stream(s, indent + "  ", v.hatY);
    s << indent << "throttle: ";
    Printer<double>::stream(s, indent + "  ", v.throttle);
    s << indent << "buttons[]" << std::endl;
    for (size_t i = 0; i < v.buttons.size(); ++i)
    {
      s << indent << "  buttons[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.buttons[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOSUB_MSGS_MESSAGE_JOYSTICK_H
