// Generated by gencpp from file robosub_msgs/ObstaclePos.msg
// DO NOT EDIT!


#ifndef ROBOSUB_MSGS_MESSAGE_OBSTACLEPOS_H
#define ROBOSUB_MSGS_MESSAGE_OBSTACLEPOS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robosub_msgs
{
template <class ContainerAllocator>
struct ObstaclePos_
{
  typedef ObstaclePos_<ContainerAllocator> Type;

  ObstaclePos_()
    : name()
    , x(0.0)
    , y(0.0)
    , z(0.0)  {
    }
  ObstaclePos_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , x(0.0)
    , y(0.0)
    , z(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;





  typedef boost::shared_ptr< ::robosub_msgs::ObstaclePos_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robosub_msgs::ObstaclePos_<ContainerAllocator> const> ConstPtr;

}; // struct ObstaclePos_

typedef ::robosub_msgs::ObstaclePos_<std::allocator<void> > ObstaclePos;

typedef boost::shared_ptr< ::robosub_msgs::ObstaclePos > ObstaclePosPtr;
typedef boost::shared_ptr< ::robosub_msgs::ObstaclePos const> ObstaclePosConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robosub_msgs::ObstaclePos_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robosub_msgs::ObstaclePos_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robosub_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'robosub_msgs': ['/home/gabrieljsss/ros/src/robosub_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robosub_msgs::ObstaclePos_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robosub_msgs::ObstaclePos_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robosub_msgs::ObstaclePos_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robosub_msgs::ObstaclePos_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robosub_msgs::ObstaclePos_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robosub_msgs::ObstaclePos_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robosub_msgs::ObstaclePos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2edff07075d48378c13052415416989c";
  }

  static const char* value(const ::robosub_msgs::ObstaclePos_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2edff07075d48378ULL;
  static const uint64_t static_value2 = 0xc13052415416989cULL;
};

template<class ContainerAllocator>
struct DataType< ::robosub_msgs::ObstaclePos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robosub_msgs/ObstaclePos";
  }

  static const char* value(const ::robosub_msgs::ObstaclePos_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robosub_msgs::ObstaclePos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::robosub_msgs::ObstaclePos_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robosub_msgs::ObstaclePos_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObstaclePos_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robosub_msgs::ObstaclePos_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robosub_msgs::ObstaclePos_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOSUB_MSGS_MESSAGE_OBSTACLEPOS_H
