// Generated by gencpp from file robosub/SetInt.msg
// DO NOT EDIT!


#ifndef ROBOSUB_MESSAGE_SETINT_H
#define ROBOSUB_MESSAGE_SETINT_H

#include <ros/service_traits.h>


#include <robosub/SetIntRequest.h>
#include <robosub/SetIntResponse.h>


namespace robosub
{

struct SetInt
{

typedef SetIntRequest Request;
typedef SetIntResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetInt
} // namespace robosub


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robosub::SetInt > {
  static const char* value()
  {
    return "65058a332cdf9eddf11f34077a0b92a4";
  }

  static const char* value(const ::robosub::SetInt&) { return value(); }
};

template<>
struct DataType< ::robosub::SetInt > {
  static const char* value()
  {
    return "robosub/SetInt";
  }

  static const char* value(const ::robosub::SetInt&) { return value(); }
};


// service_traits::MD5Sum< ::robosub::SetIntRequest> should match 
// service_traits::MD5Sum< ::robosub::SetInt > 
template<>
struct MD5Sum< ::robosub::SetIntRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robosub::SetInt >::value();
  }
  static const char* value(const ::robosub::SetIntRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robosub::SetIntRequest> should match 
// service_traits::DataType< ::robosub::SetInt > 
template<>
struct DataType< ::robosub::SetIntRequest>
{
  static const char* value()
  {
    return DataType< ::robosub::SetInt >::value();
  }
  static const char* value(const ::robosub::SetIntRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robosub::SetIntResponse> should match 
// service_traits::MD5Sum< ::robosub::SetInt > 
template<>
struct MD5Sum< ::robosub::SetIntResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robosub::SetInt >::value();
  }
  static const char* value(const ::robosub::SetIntResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robosub::SetIntResponse> should match 
// service_traits::DataType< ::robosub::SetInt > 
template<>
struct DataType< ::robosub::SetIntResponse>
{
  static const char* value()
  {
    return DataType< ::robosub::SetInt >::value();
  }
  static const char* value(const ::robosub::SetIntResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOSUB_MESSAGE_SETINT_H
