(cl:defpackage robosub-srv
  (:use )
  (:export
   "SETINT"
   "<SETINT-REQUEST>"
   "SETINT-REQUEST"
   "<SETINT-RESPONSE>"
   "SETINT-RESPONSE"
   "PNEUMATIC_STATUS"
   "<PNEUMATIC_STATUS-REQUEST>"
   "PNEUMATIC_STATUS-REQUEST"
   "<PNEUMATIC_STATUS-RESPONSE>"
   "PNEUMATIC_STATUS-RESPONSE"
  ))

