// Generated by gencpp from file robosub_msgs/Trax.msg
// DO NOT EDIT!


#ifndef ROBOSUB_MSGS_MESSAGE_TRAX_H
#define ROBOSUB_MSGS_MESSAGE_TRAX_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robosub_msgs
{
template <class ContainerAllocator>
struct Trax_
{
  typedef Trax_<ContainerAllocator> Type;

  Trax_()
    : roll(0.0)
    , pitch(0.0)
    , yaw(0.0)
    , yaw_accuracy(0)
    , calibrated(0)  {
    }
  Trax_(const ContainerAllocator& _alloc)
    : roll(0.0)
    , pitch(0.0)
    , yaw(0.0)
    , yaw_accuracy(0)
    , calibrated(0)  {
  (void)_alloc;
    }



   typedef float _roll_type;
  _roll_type roll;

   typedef float _pitch_type;
  _pitch_type pitch;

   typedef float _yaw_type;
  _yaw_type yaw;

   typedef uint8_t _yaw_accuracy_type;
  _yaw_accuracy_type yaw_accuracy;

   typedef uint8_t _calibrated_type;
  _calibrated_type calibrated;





  typedef boost::shared_ptr< ::robosub_msgs::Trax_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robosub_msgs::Trax_<ContainerAllocator> const> ConstPtr;

}; // struct Trax_

typedef ::robosub_msgs::Trax_<std::allocator<void> > Trax;

typedef boost::shared_ptr< ::robosub_msgs::Trax > TraxPtr;
typedef boost::shared_ptr< ::robosub_msgs::Trax const> TraxConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robosub_msgs::Trax_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robosub_msgs::Trax_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robosub_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'robosub_msgs': ['/home/gabrieljsss/ros/src/robosub_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robosub_msgs::Trax_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robosub_msgs::Trax_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robosub_msgs::Trax_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robosub_msgs::Trax_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robosub_msgs::Trax_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robosub_msgs::Trax_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robosub_msgs::Trax_<ContainerAllocator> >
{
  static const char* value()
  {
    return "27cd4de1f5bee264991cb280288c6ee8";
  }

  static const char* value(const ::robosub_msgs::Trax_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x27cd4de1f5bee264ULL;
  static const uint64_t static_value2 = 0x991cb280288c6ee8ULL;
};

template<class ContainerAllocator>
struct DataType< ::robosub_msgs::Trax_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robosub_msgs/Trax";
  }

  static const char* value(const ::robosub_msgs::Trax_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robosub_msgs::Trax_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 roll\n\
float32 pitch\n\
float32 yaw\n\
uint8 yaw_accuracy\n\
uint8 calibrated\n\
";
  }

  static const char* value(const ::robosub_msgs::Trax_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robosub_msgs::Trax_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.roll);
      stream.next(m.pitch);
      stream.next(m.yaw);
      stream.next(m.yaw_accuracy);
      stream.next(m.calibrated);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Trax_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robosub_msgs::Trax_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robosub_msgs::Trax_<ContainerAllocator>& v)
  {
    s << indent << "roll: ";
    Printer<float>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<float>::stream(s, indent + "  ", v.pitch);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
    s << indent << "yaw_accuracy: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.yaw_accuracy);
    s << indent << "calibrated: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.calibrated);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOSUB_MSGS_MESSAGE_TRAX_H
